/*
====================================================================
 Script     : 002_SeedUsers.sql
 Purpose    : Sample login accounts for local development / demo of
              the Staffing Management System.

 Password for every seeded account: Passw0rd!123

 PasswordHash values were generated by the exact PBKDF2 (HMAC-SHA256,
 100,000 iterations) algorithm implemented in
 StaffingManagementSystem.Infrastructure.Security.PasswordHasher, stored
 as "{iterations}.{saltBase64}.{hashBase64}". Each row uses a different
 salt/hash even though the plaintext password is the same.
====================================================================
*/

USE [StaffingManagementSystemDb];
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'admin@itmusketeers.com')
BEGIN
    INSERT INTO dbo.Users (Id, FirstName, LastName, Email, PasswordHash, Role, IsActive, CreatedAtUtc)
    VALUES (NEWID(), N'Alex', N'Morgan', N'admin@itmusketeers.com',
            N'100000.uomi0rFxmjaA8YLNM+/+9g==.52Ju9ZptuAklYEoE2Kd3vPMwlpmJ8ahxkMSRluUii0k=',
            N'Admin', 1, SYSUTCDATETIME());
END

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'recruiter@itmusketeers.com')
BEGIN
    INSERT INTO dbo.Users (Id, FirstName, LastName, Email, PasswordHash, Role, IsActive, CreatedAtUtc)
    VALUES (NEWID(), N'Priya', N'Sharma', N'recruiter@itmusketeers.com',
            N'100000.bYyx8fUABJoMZF/Lk3jolQ==.1LZtKX0/Hi65QeyCJ23zatzWvAkNJxv6QuAOTX/goEw=',
            N'Recruiter', 1, SYSUTCDATETIME());
END

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'hiringmanager@itmusketeers.com')
BEGIN
    INSERT INTO dbo.Users (Id, FirstName, LastName, Email, PasswordHash, Role, IsActive, CreatedAtUtc)
    VALUES (NEWID(), N'Daniel', N'Reyes', N'hiringmanager@itmusketeers.com',
            N'100000.Z7IK5oDN5l/2RBddj7zhJw==.NU1RKCr7u6282b18h9F+h3Tb6z/lv+jnRjmwhfhp5+M=',
            N'HiringManager', 1, SYSUTCDATETIME());
END

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'interviewer@itmusketeers.com')
BEGIN
    INSERT INTO dbo.Users (Id, FirstName, LastName, Email, PasswordHash, Role, IsActive, CreatedAtUtc)
    VALUES (NEWID(), N'Emma', N'Clarke', N'interviewer@itmusketeers.com',
            N'100000.J6cL6mS589eUJugtKTgr6Q==.kNFUJXHAU2fRDGNgM3hIYVi1fPdOhhJ2wfP6aiIDeM4=',
            N'Interviewer', 1, SYSUTCDATETIME());
END

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = N'inactive.user@itmusketeers.com')
BEGIN
    -- Demonstrates a deactivated account: login must be rejected even with the correct password.
    INSERT INTO dbo.Users (Id, FirstName, LastName, Email, PasswordHash, Role, IsActive, CreatedAtUtc)
    VALUES (NEWID(), N'Sam', N'Wilson', N'inactive.user@itmusketeers.com',
            N'100000.PNwIsyouPbbitWkoo655YQ==.eW2DEk9+YD2DsdpRbYIkA7ifkwZOQ1TXWDqZm16qkQQ=',
            N'Recruiter', 0, SYSUTCDATETIME());
END
GO
